services:
  keras:
    build:
      context: .
      dockerfile: Dockerfile-gpu
      args:
        - PASSWD=${PASSWD}
    ports:
      - '2222:22'
    volumes:
      - /data/keras-workspace:/root/Documents
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ['0', '3']
              capabilities: [gpu]

  postgres:
      image: postgres:latest
      container_name: postgres
      ports:
          - 5432:5432
      volumes:
          - /data/postgres-data/initdb.d:/docker-entrypoint-initdb.d
          - /data/postgres-data/pgdata:/var/lib/postgresql/data
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      hostname: postgres
      restart: always
      user: root

  pgadmin4:
      image: dpage/pgadmin4:latest
      container_name: pgadmin4
      ports:
          - 8000:80
      volumes:
          - /data/postgres-data/pgadmin4:/var/lib/pgadmin
      environment:
          PGADMIN_DEFAULT_EMAIL: root@example.com
          PGADMIN_DEFAULT_PASSWORD: root
      hostname: pgadmin4
      depends_on:
        - postgres
      restart: always